### ISSUE TITLE
Add patch to zabbix-patches for visibility

### ISSUE THREAD

**Issue by paskal** [v-zhuravlev/zabbix-hostmenu#2]
Hi, Vitaly!

Zabbix repo https://github.com/zabbix/zabbix-patches is about making patches available in single place, I guess your work will be available for wider audience if you'll add it to zabbix-patches repo. If you're interested, please contact me to discuss how to do it easiest way to you and prevent code splitting between same code in two repos.

**Comment by v-zhuravlev** [comment]
Sure , why not, please tell me more.
I also have another patch that worth mentioning:
https://github.com/v-zhuravlev/zbx_value_maps_on_graphs
